version: '3'
services:
  author-service:
    build: ./author-service
    ports:
      - "3001:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - BOOK_SERVICE_URL=http://book-service:3000
      - JWT_SECRET=leanCourseSecret
      - MONGO_URI=mongodb+srv://@cluster0.qssmust.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - redis

  book-service:
    build: ./book-service
    ports:
      - "3002:3000"
      - "9230:9229"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - AUTHOR_SERVICE_URL=http://author-service:3000
      - JWT_SECRET=leanCourseSecret
      - MONGO_URI=mongodb+srv://@cluster0.qssmust.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - redis

  redis:
    image: redis:alpine

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - author-service
      - book-service
